
[build.environment]
  NPM_VERSION = "6.14.8"
  NODE_VERSION = "12.16.3"

[build]
  publish = "_build/html"
  command = "make clean html"

[context.production]
  publish = "_build/html"
  command = "make clean html"

[context.deploy-preview]
  publish = "_build/html"
  command = "make clean html"
